//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accionesmejora
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public int tipo { get; set; }
        public string asunto { get; set; }
        public Nullable<System.DateTime> fecha_apertura { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public int estado { get; set; }
        public int responsable { get; set; }
        public int antecedente { get; set; }
        public Nullable<int> referencia { get; set; }
        public string referencianoconforme { get; set; }
        public int proceso { get; set; }
        public string causas { get; set; }
        public string ai_descripcion { get; set; }
        public Nullable<int> ai_responsable { get; set; }
        public Nullable<System.DateTime> ai_ffin_prevista { get; set; }
        public Nullable<System.DateTime> ai_fcierre { get; set; }
        public int ai_estado { get; set; }
        public string ai_comentario { get; set; }
        public int idcentral { get; set; }
        public int anio { get; set; }
        public int idconsecutivo { get; set; }
        public int ambito { get; set; }
        public Nullable<int> especifico { get; set; }
        public int contratista { get; set; }
        public string detectadopor { get; set; }
        public string personasinv { get; set; }
        public string descripcion { get; set; }
    }
}
