//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspecto_parametros
    {
        public int id { get; set; }
        public int idCentral { get; set; }
        public Nullable<decimal> Mwhb1 { get; set; }
        public Nullable<decimal> Mwhb2 { get; set; }
        public Nullable<decimal> Mwhb3 { get; set; }
        public Nullable<decimal> Mwhb4 { get; set; }
        public Nullable<decimal> Mwhb5 { get; set; }
        public Nullable<decimal> Mwhb6 { get; set; }
        public Nullable<decimal> hAnioGE1 { get; set; }
        public Nullable<decimal> hAnioGE2 { get; set; }
        public Nullable<decimal> hAnioGE3 { get; set; }
        public Nullable<decimal> hAnioGE4 { get; set; }
        public Nullable<decimal> hAnioGE5 { get; set; }
        public Nullable<decimal> hAnioGE6 { get; set; }
        public Nullable<decimal> kmAnio1 { get; set; }
        public Nullable<decimal> kmAnio2 { get; set; }
        public Nullable<decimal> kmAnio3 { get; set; }
        public Nullable<decimal> kmAnio4 { get; set; }
        public Nullable<decimal> kmAnio5 { get; set; }
        public Nullable<decimal> kmAnio6 { get; set; }
        public Nullable<decimal> m3Hora1 { get; set; }
        public Nullable<decimal> m3Hora2 { get; set; }
        public Nullable<decimal> m3Hora3 { get; set; }
        public Nullable<decimal> m3Hora4 { get; set; }
        public Nullable<decimal> m3Hora5 { get; set; }
        public Nullable<decimal> m3Hora6 { get; set; }
        public Nullable<decimal> hfuncAnio1 { get; set; }
        public Nullable<decimal> hfuncAnio2 { get; set; }
        public Nullable<decimal> hfuncAnio3 { get; set; }
        public Nullable<decimal> hfuncAnio4 { get; set; }
        public Nullable<decimal> hfuncAnio5 { get; set; }
        public Nullable<decimal> hfuncAnio6 { get; set; }
        public Nullable<decimal> numtrabAnio1 { get; set; }
        public Nullable<decimal> numtrabAnio2 { get; set; }
        public Nullable<decimal> numtrabAnio3 { get; set; }
        public Nullable<decimal> numtrabAnio4 { get; set; }
        public Nullable<decimal> numtrabAnio5 { get; set; }
        public Nullable<decimal> numtrabAnio6 { get; set; }
        public Nullable<decimal> m3aguadesaladaAnio1 { get; set; }
        public Nullable<decimal> m3aguadesaladaAnio2 { get; set; }
        public Nullable<decimal> m3aguadesaladaAnio3 { get; set; }
        public Nullable<decimal> m3aguadesaladaAnio4 { get; set; }
        public Nullable<decimal> m3aguadesaladaAnio5 { get; set; }
        public Nullable<decimal> m3aguadesaladaAnio6 { get; set; }
        public Nullable<decimal> trabcanteraAnio1 { get; set; }
        public Nullable<decimal> trabcanteraAnio2 { get; set; }
        public Nullable<decimal> trabcanteraAnio3 { get; set; }
        public Nullable<decimal> trabcanteraAnio4 { get; set; }
        public Nullable<decimal> trabcanteraAnio5 { get; set; }
        public Nullable<decimal> trabcanteraAnio6 { get; set; }
    }
}
