//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspecto_tipo
    {
        public int id { get; set; }
        public int Grupo { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Impacto { get; set; }
        public string Descripcion { get; set; }
        public string Unidad { get; set; }
        public Nullable<int> RE_Peligroso { get; set; }
        public Nullable<bool> relativoMwhb { get; set; }
        public Nullable<bool> relativohAnioGE { get; set; }
        public Nullable<bool> relativokmAnio { get; set; }
        public Nullable<bool> relativom3Hora { get; set; }
        public Nullable<bool> relativohfuncAnio { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> idconsecutivo { get; set; }
        public Nullable<int> foco { get; set; }
        public Nullable<bool> relativonumtrab { get; set; }
        public Nullable<bool> relativom3aguadeitsalada { get; set; }
        public Nullable<bool> relativotrabcantera { get; set; }
        public Nullable<bool> relativono { get; set; }
    }
}
