//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspecto_parametros_log
    {
        public int id { get; set; }
        public int idCentral { get; set; }
        public int anio { get; set; }
        public Nullable<decimal> Mwhb { get; set; }
        public Nullable<decimal> hAnioGE { get; set; }
        public Nullable<decimal> kmAnio { get; set; }
        public Nullable<decimal> m3Hora { get; set; }
        public Nullable<decimal> hfunc { get; set; }
        public Nullable<decimal> numtrab { get; set; }
        public Nullable<decimal> m3aguadesalada { get; set; }
        public Nullable<decimal> trabcantera { get; set; }
    }
}
