//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspecto_parametro_valoracion_log
    {
        public int id { get; set; }
        public Nullable<int> anio { get; set; }
        public Nullable<int> id_registro { get; set; }
        public Nullable<decimal> mes1 { get; set; }
        public Nullable<decimal> mes2 { get; set; }
        public Nullable<decimal> mes3 { get; set; }
        public Nullable<decimal> mes4 { get; set; }
        public Nullable<decimal> mes5 { get; set; }
        public Nullable<decimal> mes6 { get; set; }
        public Nullable<decimal> mes7 { get; set; }
        public Nullable<decimal> mes8 { get; set; }
        public Nullable<decimal> mes9 { get; set; }
        public Nullable<decimal> mes10 { get; set; }
        public Nullable<decimal> mes11 { get; set; }
        public Nullable<decimal> mes12 { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<decimal> valorcalculado { get; set; }
        public Nullable<decimal> variacion { get; set; }
        public Nullable<decimal> acercamiento { get; set; }
        public Nullable<decimal> referencia { get; set; }
        public Nullable<int> naturaleza { get; set; }
        public Nullable<int> origen { get; set; }
        public Nullable<int> significancia { get; set; }
        public Nullable<decimal> resmagnitud { get; set; }
        public Nullable<decimal> resnaturaleza { get; set; }
        public Nullable<decimal> resorigen { get; set; }
        public Nullable<decimal> RU_DiaRef { get; set; }
        public Nullable<decimal> RU_TardeRef { get; set; }
        public Nullable<decimal> RU_NocheRef { get; set; }
        public Nullable<decimal> RU_Dia { get; set; }
        public Nullable<decimal> RU_Tarde { get; set; }
        public Nullable<decimal> RU_Noche { get; set; }
        public Nullable<int> magnitud { get; set; }
        public Nullable<decimal> referenciasup { get; set; }
        public Nullable<int> id_aspecto { get; set; }
        public Nullable<int> id_parametro { get; set; }
    }
}
