//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspecto_valoracion_log
    {
        public int id { get; set; }
        public int idAspecto { get; set; }
        public int idCentral { get; set; }
        public Nullable<int> anio { get; set; }
        public Nullable<decimal> valoranio { get; set; }
        public Nullable<decimal> valorcalculado { get; set; }
        public Nullable<decimal> variacion { get; set; }
        public Nullable<decimal> acercamiento { get; set; }
        public Nullable<decimal> referencia { get; set; }
        public Nullable<int> naturaleza { get; set; }
        public Nullable<int> origen { get; set; }
        public Nullable<int> significancia { get; set; }
        public Nullable<decimal> datoabsoluto { get; set; }
        public Nullable<decimal> RU_DiaRef { get; set; }
        public Nullable<decimal> RU_TardeRef { get; set; }
        public Nullable<decimal> RU_NocheRef { get; set; }
        public Nullable<decimal> RU_Dia { get; set; }
        public Nullable<decimal> RU_Tarde { get; set; }
        public Nullable<decimal> RU_Noche { get; set; }
        public Nullable<int> magnitud { get; set; }
        public string IN_Proveedor { get; set; }
        public string IN_ServicioPrestado { get; set; }
        public Nullable<int> IN_TipoActividad { get; set; }
        public Nullable<int> IN_Aspecto { get; set; }
        public Nullable<int> queja { get; set; }
        public string quejaobs { get; set; }
        public Nullable<decimal> resmagnitud { get; set; }
        public Nullable<decimal> resnaturaleza { get; set; }
        public Nullable<decimal> resorigen { get; set; }
        public Nullable<int> id_registro { get; set; }
    }
}
