//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class banco_icono
    {
        public int Id { get; set; }
        public string Codificacion { get; set; }
        public string Descripcion { get; set; }
        public string Ruta_Icono { get; set; }
        public bool tamano { get; set; }
    }
}
