//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comunicacion
    {
        public int id { get; set; }
        public string idcomunicacion { get; set; }
        public int idcentral { get; set; }
        public int tipo { get; set; }
        public int clasificacion { get; set; }
        public int stakeholder { get; set; }
        public Nullable<System.DateTime> fechainicio { get; set; }
        public int canal { get; set; }
        public Nullable<int> eficacia { get; set; }
        public Nullable<System.DateTime> fechafin { get; set; }
        public int idconsecutivo { get; set; }
        public string descripcion { get; set; }
        public string descripcionres { get; set; }
        public string asunto { get; set; }
        public string remitente { get; set; }
    }
}
