//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuestionario
    {
        public int id { get; set; }
        public int idOrganizacion { get; set; }
        public Nullable<System.DateTime> fechavalidez { get; set; }
        public Nullable<bool> organizacionvalidada { get; set; }
        public Nullable<bool> cuestionariovalidado { get; set; }
        public Nullable<int> anio { get; set; }
    }
}
