//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class despliegue
    {
        public int id { get; set; }
        public int idObjetivo { get; set; }
        public string NumeroAccionDespliegue { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaEstimada { get; set; }
        public Nullable<System.DateTime> FechaReal { get; set; }
        public Nullable<int> Responsable { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Recursos { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> idconsecutivo { get; set; }
        public Nullable<int> Porcentaje { get; set; }
    }
}
