//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentos_riesgos
    {
        public int id { get; set; }
        public Nullable<int> id_centro { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechageneracion { get; set; }
        public string rutaDescarga { get; set; }
        public Nullable<int> revision { get; set; }
        public Nullable<bool> esborrador { get; set; }
    }
}
