//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentacion
    {
        public int idFichero { get; set; }
        public Nullable<int> estado { get; set; }
        public string nombre_fichero { get; set; }
        public Nullable<int> tipo { get; set; }
        public string enlace { get; set; }
        public Nullable<System.DateTime> fecha_aprobacion { get; set; }
        public Nullable<System.DateTime> fecha_publicacion { get; set; }
        public string titulo { get; set; }
        public Nullable<int> nivel { get; set; }
        public Nullable<int> tipocentral { get; set; }
        public Nullable<int> idcentro { get; set; }
        public Nullable<int> idproceso { get; set; }
        public string cod_fichero { get; set; }
        public string version { get; set; }
    }
}
