//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento_ambiental
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fechaevento { get; set; }
        public int tipo { get; set; }
        public int matrizprincipal { get; set; }
        public Nullable<int> matrizsecundaria { get; set; }
        public string organizacion { get; set; }
        public string pais { get; set; }
        public string unidadnegocio { get; set; }
        public int idcentral { get; set; }
        public int idtecnologia { get; set; }
        public int companiainvolucrada { get; set; }
        public string companiaenel { get; set; }
        public Nullable<int> claseevento_sec2 { get; set; }
        public string extension_sec2 { get; set; }
        public Nullable<int> impacto_sec2 { get; set; }
        public string localizacion_sec2 { get; set; }
        public string descripcion_sec2 { get; set; }
        public string causa_sec2 { get; set; }
        public string accionesinmediatas_sec2 { get; set; }
        public string descripcion_sec3 { get; set; }
        public string demandante_sec3 { get; set; }
        public Nullable<int> tipodemantante_sec3 { get; set; }
        public Nullable<int> tipocriticidad_sec3 { get; set; }
        public string infoadicional { get; set; }
        public string empresacontratista { get; set; }
    }
}
