//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento_seguridad
    {
        public int id { get; set; }
        public int tipo { get; set; }
        public int severidad { get; set; }
        public int personalafectado { get; set; }
        public int organizacion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public string unidadnegocio { get; set; }
        public int idcentral { get; set; }
        public string compania { get; set; }
        public string ie_region { get; set; }
        public string ie_localizacion { get; set; }
        public string ie_descripcion { get; set; }
        public string pa_nombre { get; set; }
        public string pa_apellido { get; set; }
        public int pa_genero { get; set; }
        public int pa_edad { get; set; }
        public string pa_puesto { get; set; }
        public string pa_nacionalidad { get; set; }
        public string id_informemedico { get; set; }
        public string id_diasconv_primerpron { get; set; }
        public int te_tipo { get; set; }
        public int te_subtipo { get; set; }
        public int te_categorizacion { get; set; }
        public string te_causa { get; set; }
        public string te_accionesinm { get; set; }
        public string ic_nombreempresa { get; set; }
        public string ic_actividad { get; set; }
        public string ic_personaref { get; set; }
        public string ic_telefono { get; set; }
        public string ic_email { get; set; }
        public string ia_horario { get; set; }
        public string ia_desde { get; set; }
        public string ia_hacia { get; set; }
        public string ia_lugar { get; set; }
        public string ia_medio { get; set; }
        public string ia_propiedadmediotransporte { get; set; }
        public string ia_causa { get; set; }
        public Nullable<int> baja { get; set; }
        public Nullable<System.DateTime> fechabaja { get; set; }
        public Nullable<System.TimeSpan> horaaccidente { get; set; }
        public string pa_antiguedadempresa { get; set; }
        public string pa_antiguedadcategoria { get; set; }
        public Nullable<int> pa_tipocontrato { get; set; }
        public Nullable<int> pa_accidentesant { get; set; }
        public Nullable<int> pa_numacc { get; set; }
        public Nullable<int> pa_diasbaja { get; set; }
        public Nullable<System.DateTime> pa_fechamodformacion { get; set; }
        public string pa_nombreultformacion { get; set; }
        public Nullable<int> id_reqasistencia { get; set; }
        public string id_asistenciaen { get; set; }
        public string id_personalsanitario { get; set; }
        public string id_naturalezalesion { get; set; }
        public string id_localizacionanatomica { get; set; }
        public string id_agentelesion { get; set; }
        public Nullable<int> id_envmutua { get; set; }
        public string id_mutua { get; set; }
        public string id_localidadmutua { get; set; }
        public Nullable<int> id_envcs { get; set; }
        public string id_centrosanitario { get; set; }
        public string id_localidadcs { get; set; }
        public string id_mandodirecto { get; set; }
        public string id_testigo1 { get; set; }
        public string id_testigo2 { get; set; }
        public string id_testigo3 { get; set; }
        public Nullable<int> ic_empcontratista { get; set; }
        public string ic_subcontrata { get; set; }
        public string ic_personalsanit { get; set; }
        public string ic_domicilio { get; set; }
        public string ic_cif { get; set; }
        public string ic_localidad { get; set; }
    }
}
