//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class formacion
    {
        public int id { get; set; }
        public int anio { get; set; }
        public string codigo { get; set; }
        public string denominacion { get; set; }
        public string planificacion_inicial { get; set; }
        public Nullable<System.DateTime> fecha_registro_inicio { get; set; }
        public Nullable<System.DateTime> fecha_registro_ejecutado { get; set; }
        public string planificacion_ejecutada { get; set; }
        public Nullable<int> valoracion_eficacia { get; set; }
        public int idconsecutivo { get; set; }
        public int idcentral { get; set; }
        public Nullable<int> actividadesejecutadas { get; set; }
        public Nullable<int> actividadesplanificadas { get; set; }
        public Nullable<int> horascalidad { get; set; }
        public Nullable<int> horasmedioambiente { get; set; }
        public Nullable<int> horasseguridadsalud { get; set; }
        public Nullable<int> horasotrasareas { get; set; }
        public string analisiscausasnorealiz { get; set; }
        public string analisiscausasnoefectivas { get; set; }
        public string observaciones { get; set; }
    }
}
