//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class indicadores
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string MetodoMedicion { get; set; }
        public Nullable<int> Operador1 { get; set; }
        public string Operacion1 { get; set; }
        public Nullable<int> Operador2 { get; set; }
        public string Operacion2 { get; set; }
        public Nullable<int> Operador3 { get; set; }
        public Nullable<bool> ValorNumerico { get; set; }
        public string Unidad { get; set; }
        public Nullable<int> ProcesoAsociado { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> tecnologia { get; set; }
        public string Periodicidad { get; set; }
        public Nullable<int> especifico { get; set; }
        public Nullable<int> tendencia { get; set; }
        public string listadoCentrales { get; set; }
        public Nullable<decimal> Operador1Constante { get; set; }
        public Nullable<decimal> Operador2Constante { get; set; }
        public Nullable<decimal> Operador3Constante { get; set; }
    }
}
