//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class indicadores_planificacion
    {
        public int Id { get; set; }
        public int IdIndicador { get; set; }
        public string FuenteInformacion { get; set; }
        public string Operación { get; set; }
        public Nullable<int> idCentral { get; set; }
        public string CodIndicador { get; set; }
        public Nullable<int> idconsecutivo { get; set; }
        public Nullable<int> anio { get; set; }
    }
}
