//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class indicadores_hojadedatos_valores
    {
        public int Id { get; set; }
        public int CodIndiHojaDatos { get; set; }
        public int anio { get; set; }
        public Nullable<decimal> valor1 { get; set; }
        public Nullable<decimal> valor2 { get; set; }
        public Nullable<decimal> valor3 { get; set; }
        public Nullable<decimal> valor4 { get; set; }
        public Nullable<decimal> valor5 { get; set; }
        public Nullable<decimal> valor6 { get; set; }
        public Nullable<decimal> valor7 { get; set; }
        public Nullable<decimal> valor8 { get; set; }
        public Nullable<decimal> valor9 { get; set; }
        public Nullable<decimal> valor10 { get; set; }
        public Nullable<decimal> valor11 { get; set; }
        public Nullable<decimal> valor12 { get; set; }
        public Nullable<int> idcentral { get; set; }
        public Nullable<bool> baja { get; set; }
    }
}
