//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lista_final_personas
    {
        public int Id { get; set; }
        public int Id_Personas { get; set; }
        public string Nº_Empleado { get; set; }
        public string Perfil_de_riesgo { get; set; }
        public string Actividad_Funcional { get; set; }
        public string DNI { get; set; }
        public string Nombre { get; set; }
        public int Usuario_Propietario_Lista { get; set; }
    }
}
