//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class localidad
    {
        public int id_consecutivo { get; set; }
        public int id_provincia { get; set; }
        public int id_poblacion { get; set; }
        public string nombre_localidad { get; set; }
    }
}
