//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medidaspreventivas_imagenes
    {
        public int id { get; set; }
        public int id_medida { get; set; }
        public string rutaImagen { get; set; }
        public Nullable<int> id_centro { get; set; }
        public Nullable<bool> tamano { get; set; }
    }
}
