//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DIMASSTEntities : DbContext
    {
        public DIMASSTEntities()
            : base("name=DIMASSTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accionesmejora> accionesmejora { get; set; }
        public virtual DbSet<accionmejora_accion> accionmejora_accion { get; set; }
        public virtual DbSet<accionmejora_documento> accionmejora_documento { get; set; }
        public virtual DbSet<accionmejora_referencial> accionmejora_referencial { get; set; }
        public virtual DbSet<ambitos> ambitos { get; set; }
        public virtual DbSet<aspecto_grupo> aspecto_grupo { get; set; }
        public virtual DbSet<aspecto_parametro> aspecto_parametro { get; set; }
        public virtual DbSet<aspecto_parametro_valoracion> aspecto_parametro_valoracion { get; set; }
        public virtual DbSet<aspecto_parametro_valoracion_log> aspecto_parametro_valoracion_log { get; set; }
        public virtual DbSet<aspecto_parametros> aspecto_parametros { get; set; }
        public virtual DbSet<aspecto_parametros_log> aspecto_parametros_log { get; set; }
        public virtual DbSet<aspecto_subgrupo> aspecto_subgrupo { get; set; }
        public virtual DbSet<aspecto_tipo> aspecto_tipo { get; set; }
        public virtual DbSet<aspecto_valoracion> aspecto_valoracion { get; set; }
        public virtual DbSet<aspecto_valoracion_log> aspecto_valoracion_log { get; set; }
        public virtual DbSet<auditores> auditores { get; set; }
        public virtual DbSet<auditorias> auditorias { get; set; }
        public virtual DbSet<auditorias_auditores> auditorias_auditores { get; set; }
        public virtual DbSet<auditorias_observador> auditorias_observador { get; set; }
        public virtual DbSet<auditorias_programa> auditorias_programa { get; set; }
        public virtual DbSet<auditorias_referenciales> auditorias_referenciales { get; set; }
        public virtual DbSet<comunicacion> comunicacion { get; set; }
        public virtual DbSet<comunicacion_canales> comunicacion_canales { get; set; }
        public virtual DbSet<comunicacion_clasificacion> comunicacion_clasificacion { get; set; }
        public virtual DbSet<comunicacion_documentos> comunicacion_documentos { get; set; }
        public virtual DbSet<comunicacion_procesos> comunicacion_procesos { get; set; }
        public virtual DbSet<comunicacion_tipos> comunicacion_tipos { get; set; }
        public virtual DbSet<comunidad_autonoma> comunidad_autonoma { get; set; }
        public virtual DbSet<cualificaciones> cualificaciones { get; set; }
        public virtual DbSet<cuestionario> cuestionario { get; set; }
        public virtual DbSet<despliegue> despliegue { get; set; }
        public virtual DbSet<documentacion> documentacion { get; set; }
        public virtual DbSet<documentacion_hist> documentacion_hist { get; set; }
        public virtual DbSet<documentos_programa> documentos_programa { get; set; }
        public virtual DbSet<emergencias> emergencias { get; set; }
        public virtual DbSet<enlaces> enlaces { get; set; }
        public virtual DbSet<evaluacionriesgos> evaluacionriesgos { get; set; }
        public virtual DbSet<evaluacionriesgos_elaboradopor> evaluacionriesgos_elaboradopor { get; set; }
        public virtual DbSet<evaluacionriesgos_tipodoc> evaluacionriesgos_tipodoc { get; set; }
        public virtual DbSet<evento_ambiental> evento_ambiental { get; set; }
        public virtual DbSet<evento_ambiental_documentos> evento_ambiental_documentos { get; set; }
        public virtual DbSet<evento_ambiental_foto> evento_ambiental_foto { get; set; }
        public virtual DbSet<evento_ambiental_matriz> evento_ambiental_matriz { get; set; }
        public virtual DbSet<evento_ambiental_tipo> evento_ambiental_tipo { get; set; }
        public virtual DbSet<evento_calidad> evento_calidad { get; set; }
        public virtual DbSet<evento_seguridad> evento_seguridad { get; set; }
        public virtual DbSet<evento_seguridad_documentos> evento_seguridad_documentos { get; set; }
        public virtual DbSet<evento_seguridad_foto> evento_seguridad_foto { get; set; }
        public virtual DbSet<evento_seguridad_severidad> evento_seguridad_severidad { get; set; }
        public virtual DbSet<evento_seguridad_subtipoevento> evento_seguridad_subtipoevento { get; set; }
        public virtual DbSet<evento_seguridad_tipo> evento_seguridad_tipo { get; set; }
        public virtual DbSet<evento_seguridad_tipoevento> evento_seguridad_tipoevento { get; set; }
        public virtual DbSet<evidencias> evidencias { get; set; }
        public virtual DbSet<ficheros> ficheros { get; set; }
        public virtual DbSet<formacion> formacion { get; set; }
        public virtual DbSet<imagenes> imagenes { get; set; }
        public virtual DbSet<indicador_centrales> indicador_centrales { get; set; }
        public virtual DbSet<indicadores> indicadores { get; set; }
        public virtual DbSet<indicadores_hojadedatos> indicadores_hojadedatos { get; set; }
        public virtual DbSet<indicadores_hojadedatos_valores> indicadores_hojadedatos_valores { get; set; }
        public virtual DbSet<indicadores_imputacion> indicadores_imputacion { get; set; }
        public virtual DbSet<indicadores_planificacion> indicadores_planificacion { get; set; }
        public virtual DbSet<informesseguridad> informesseguridad { get; set; }
        public virtual DbSet<informesseguridad_elaboradopor> informesseguridad_elaboradopor { get; set; }
        public virtual DbSet<informesseguridad_tipodoc> informesseguridad_tipodoc { get; set; }
        public virtual DbSet<localidad> localidad { get; set; }
        public virtual DbSet<log> log { get; set; }
        public virtual DbSet<materialdivulgativo> materialdivulgativo { get; set; }
        public virtual DbSet<materialdivulgativo_riesgos> materialdivulgativo_riesgos { get; set; }
        public virtual DbSet<materialdivulgativo_tipodoc> materialdivulgativo_tipodoc { get; set; }
        public virtual DbSet<modulos> modulos { get; set; }
        public virtual DbSet<normas> normas { get; set; }
        public virtual DbSet<noticias> noticias { get; set; }
        public virtual DbSet<objetivo_centrales> objetivo_centrales { get; set; }
        public virtual DbSet<objetivo_indicadorproceso> objetivo_indicadorproceso { get; set; }
        public virtual DbSet<objetivo_tecnologias> objetivo_tecnologias { get; set; }
        public virtual DbSet<objetivos> objetivos { get; set; }
        public virtual DbSet<objetivos_procesos> objetivos_procesos { get; set; }
        public virtual DbSet<pais> pais { get; set; }
        public virtual DbSet<partes> partes { get; set; }
        public virtual DbSet<perfil> perfil { get; set; }
        public virtual DbSet<procesos> procesos { get; set; }
        public virtual DbSet<provincia> provincia { get; set; }
        public virtual DbSet<referenciales> referenciales { get; set; }
        public virtual DbSet<requisitoslegales> requisitoslegales { get; set; }
        public virtual DbSet<reuniones> reuniones { get; set; }
        public virtual DbSet<reuniones_documentos> reuniones_documentos { get; set; }
        public virtual DbSet<reuniones_participantes> reuniones_participantes { get; set; }
        public virtual DbSet<revision_energetica> revision_energetica { get; set; }
        public virtual DbSet<Riesgos> Riesgos { get; set; }
        public virtual DbSet<riesgos_categorias> riesgos_categorias { get; set; }
        public virtual DbSet<riesgos_stakeholders> riesgos_stakeholders { get; set; }
        public virtual DbSet<riesgos_tipologias> riesgos_tipologias { get; set; }
        public virtual DbSet<satisfaccion> satisfaccion { get; set; }
        public virtual DbSet<stakeholders_nivel1> stakeholders_nivel1 { get; set; }
        public virtual DbSet<stakeholders_nivel2> stakeholders_nivel2 { get; set; }
        public virtual DbSet<stakeholders_nivel3> stakeholders_nivel3 { get; set; }
        public virtual DbSet<stakeholders_nivel4> stakeholders_nivel4 { get; set; }
        public virtual DbSet<tipo_accionesmejora> tipo_accionesmejora { get; set; }
        public virtual DbSet<tipodocumento> tipodocumento { get; set; }
        public virtual DbSet<usuario_centros> usuario_centros { get; set; }
        public virtual DbSet<VISTA_AccionMejora_Accion> VISTA_AccionMejora_Accion { get; set; }
        public virtual DbSet<Vista_AccionMejoraFicha> Vista_AccionMejoraFicha { get; set; }
        public virtual DbSet<VISTA_AlertaEventos> VISTA_AlertaEventos { get; set; }
        public virtual DbSet<VISTA_AspectosDesplegable> VISTA_AspectosDesplegable { get; set; }
        public virtual DbSet<VISTA_AspectosTipo> VISTA_AspectosTipo { get; set; }
        public virtual DbSet<VISTA_AspectosValoracion> VISTA_AspectosValoracion { get; set; }
        public virtual DbSet<VISTA_AspectoTipo> VISTA_AspectoTipo { get; set; }
        public virtual DbSet<VISTA_Auditores> VISTA_Auditores { get; set; }
        public virtual DbSet<VISTA_AuditoriaObservadores> VISTA_AuditoriaObservadores { get; set; }
        public virtual DbSet<VISTA_AuditoriaReferenciales> VISTA_AuditoriaReferenciales { get; set; }
        public virtual DbSet<VISTA_Auditorias> VISTA_Auditorias { get; set; }
        public virtual DbSet<VISTA_CalendarioEventos> VISTA_CalendarioEventos { get; set; }
        public virtual DbSet<VISTA_Comunicaciones> VISTA_Comunicaciones { get; set; }
        public virtual DbSet<VISTA_Despliegue> VISTA_Despliegue { get; set; }
        public virtual DbSet<VISTA_DocumentacionVersion> VISTA_DocumentacionVersion { get; set; }
        public virtual DbSet<VISTA_EvalRiesgos> VISTA_EvalRiesgos { get; set; }
        public virtual DbSet<VISTA_Eventos_Seguridad> VISTA_Eventos_Seguridad { get; set; }
        public virtual DbSet<VISTA_Indicadores> VISTA_Indicadores { get; set; }
        public virtual DbSet<VISTA_Indicadores_Centros> VISTA_Indicadores_Centros { get; set; }
        public virtual DbSet<VISTA_IndicadoresAfectadosParametro> VISTA_IndicadoresAfectadosParametro { get; set; }
        public virtual DbSet<VISTA_IndicadoresFichaDireccion> VISTA_IndicadoresFichaDireccion { get; set; }
        public virtual DbSet<VISTA_IndicadoresPlanificados> VISTA_IndicadoresPlanificados { get; set; }
        public virtual DbSet<VISTA_ListadoIndicadores> VISTA_ListadoIndicadores { get; set; }
        public virtual DbSet<VISTA_ListarAccionesMejora> VISTA_ListarAccionesMejora { get; set; }
        public virtual DbSet<VISTA_ListarAccionesMejoraFicha> VISTA_ListarAccionesMejoraFicha { get; set; }
        public virtual DbSet<VISTA_ListarCentrales> VISTA_ListarCentrales { get; set; }
        public virtual DbSet<VISTA_ListarCentrosAsignados> VISTA_ListarCentrosAsignados { get; set; }
        public virtual DbSet<VISTA_ListarCentrosSede> VISTA_ListarCentrosSede { get; set; }
        public virtual DbSet<VISTA_ListarComunidades> VISTA_ListarComunidades { get; set; }
        public virtual DbSet<VISTA_ListarComunidadesEdicion> VISTA_ListarComunidadesEdicion { get; set; }
        public virtual DbSet<VISTA_ListarEmergencias> VISTA_ListarEmergencias { get; set; }
        public virtual DbSet<VISTA_ListarEnlaces> VISTA_ListarEnlaces { get; set; }
        public virtual DbSet<VISTA_ListarEventosAmbientales> VISTA_ListarEventosAmbientales { get; set; }
        public virtual DbSet<VISTA_ListarEventosCalidad> VISTA_ListarEventosCalidad { get; set; }
        public virtual DbSet<VISTA_ListarInfSeg> VISTA_ListarInfSeg { get; set; }
        public virtual DbSet<VISTA_ListarLogEvaluacionesFoco> VISTA_ListarLogEvaluacionesFoco { get; set; }
        public virtual DbSet<VISTA_ListarLogEvaluacionesParametro> VISTA_ListarLogEvaluacionesParametro { get; set; }
        public virtual DbSet<VISTA_ListarLogParametrosFocos> VISTA_ListarLogParametrosFocos { get; set; }
        public virtual DbSet<VISTA_ListarMateriales> VISTA_ListarMateriales { get; set; }
        public virtual DbSet<VISTA_ListarPaises> VISTA_ListarPaises { get; set; }
        public virtual DbSet<VISTA_ListarParametrosTipoAspecto> VISTA_ListarParametrosTipoAspecto { get; set; }
        public virtual DbSet<VISTA_ListarProvincias> VISTA_ListarProvincias { get; set; }
        public virtual DbSet<VISTA_ListarRevisionesEnergeticas> VISTA_ListarRevisionesEnergeticas { get; set; }
        public virtual DbSet<VISTA_ListarSatisfaccion> VISTA_ListarSatisfaccion { get; set; }
        public virtual DbSet<VISTA_ListarTipoDocumento> VISTA_ListarTipoDocumento { get; set; }
        public virtual DbSet<VISTA_ListarUsuarios> VISTA_ListarUsuarios { get; set; }
        public virtual DbSet<VISTA_MaestroAspectos> VISTA_MaestroAspectos { get; set; }
        public virtual DbSet<VISTA_Objetivos> VISTA_Objetivos { get; set; }
        public virtual DbSet<VISTA_ObtenerDocumentacion> VISTA_ObtenerDocumentacion { get; set; }
        public virtual DbSet<VISTA_ObtenerLicenciaActual> VISTA_ObtenerLicenciaActual { get; set; }
        public virtual DbSet<VISTA_ParametrosInd> VISTA_ParametrosInd { get; set; }
        public virtual DbSet<VISTA_RequisitosLegales> VISTA_RequisitosLegales { get; set; }
        public virtual DbSet<VISTA_ReunionParticipantes> VISTA_ReunionParticipantes { get; set; }
        public virtual DbSet<VISTA_Riesgo> VISTA_Riesgo { get; set; }
        public virtual DbSet<VISTA_Riesgos> VISTA_Riesgos { get; set; }
        public virtual DbSet<VISTA_StakeholdersN2> VISTA_StakeholdersN2 { get; set; }
        public virtual DbSet<VISTA_StakeholdersN3> VISTA_StakeholdersN3 { get; set; }
        public virtual DbSet<VISTA_StakeholdersN4> VISTA_StakeholdersN4 { get; set; }
        public virtual DbSet<VISTA_UltimasMediciones> VISTA_UltimasMediciones { get; set; }
        public virtual DbSet<VISTA_ObtenerUsuario> VISTA_ObtenerUsuario { get; set; }
        public virtual DbSet<tipocentral> tipocentral { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<centros> centros { get; set; }
        public virtual DbSet<tecnologias> tecnologias { get; set; }
        public virtual DbSet<areanivel1> areanivel1 { get; set; }
        public virtual DbSet<areanivel2> areanivel2 { get; set; }
        public virtual DbSet<areanivel3> areanivel3 { get; set; }
        public virtual DbSet<zonas> zonas { get; set; }
        public virtual DbSet<agrupacion> agrupacion { get; set; }
        public virtual DbSet<matriz_inicial> matriz_inicial { get; set; }
        public virtual DbSet<tecnologias_centros> tecnologias_centros { get; set; }
        public virtual DbSet<version_matriz> version_matriz { get; set; }
        public virtual DbSet<zonas_tipotecnologia> zonas_tipotecnologia { get; set; }
        public virtual DbSet<centros_agrupacion> centros_agrupacion { get; set; }
        public virtual DbSet<centros_zonas> centros_zonas { get; set; }
        public virtual DbSet<medidas_preventivas> medidas_preventivas { get; set; }
        public virtual DbSet<riesgos_situaciones> riesgos_situaciones { get; set; }
        public virtual DbSet<medidas_generales> medidas_generales { get; set; }
        public virtual DbSet<parametrica_medidas> parametrica_medidas { get; set; }
        public virtual DbSet<medidas_apartados> medidas_apartados { get; set; }
        public virtual DbSet<descripcion_centro> descripcion_centro { get; set; }
        public virtual DbSet<areas_imagenes> areas_imagenes { get; set; }
        public virtual DbSet<submedidas_preventivas> submedidas_preventivas { get; set; }
        public virtual DbSet<areas2_imagenes> areas2_imagenes { get; set; }
        public virtual DbSet<equipos_imagenes> equipos_imagenes { get; set; }
        public virtual DbSet<medidaspreventivas_imagenes> medidaspreventivas_imagenes { get; set; }
        public virtual DbSet<descripcion_general> descripcion_general { get; set; }
        public virtual DbSet<areanivel4> areanivel4 { get; set; }
        public virtual DbSet<areas4_imagenes> areas4_imagenes { get; set; }
        public virtual DbSet<medidas_apartados_generales> medidas_apartados_generales { get; set; }
        public virtual DbSet<medidas_generales_imagenes> medidas_generales_imagenes { get; set; }
        public virtual DbSet<riesgos_medidas> riesgos_medidas { get; set; }
        public virtual DbSet<tipo_riesgos_critico> tipo_riesgos_critico { get; set; }
        public virtual DbSet<tipos_riesgos> tipos_riesgos { get; set; }
        public virtual DbSet<VISTA_tipos_riesgos> VISTA_tipos_riesgos { get; set; }
        public virtual DbSet<VISTA_ListaCentroTecnologia> VISTA_ListaCentroTecnologia { get; set; }
        public virtual DbSet<VISTA_ListaCentroZona> VISTA_ListaCentroZona { get; set; }
        public virtual DbSet<VISTA_ListaCentroZonaAgrupacion> VISTA_ListaCentroZonaAgrupacion { get; set; }
        public virtual DbSet<matriz_centro> matriz_centro { get; set; }
        public virtual DbSet<medidas_apartadosV2> medidas_apartadosV2 { get; set; }
        public virtual DbSet<VISTA_tipo_riesgos_critico> VISTA_tipo_riesgos_critico { get; set; }
        public virtual DbSet<matriz_centro_critico> matriz_centro_critico { get; set; }
        public virtual DbSet<tecnologias_tiposRiesgosCriticos> tecnologias_tiposRiesgosCriticos { get; set; }
        public virtual DbSet<documentos_riesgos_criticos> documentos_riesgos_criticos { get; set; }
        public virtual DbSet<documento_historico_criticos> documento_historico_criticos { get; set; }
        public virtual DbSet<documento_historico> documento_historico { get; set; }
        public virtual DbSet<documentos_riesgos> documentos_riesgos { get; set; }
        public virtual DbSet<personas> personas { get; set; }
        public virtual DbSet<lista_final_personas> lista_final_personas { get; set; }
        public virtual DbSet<banco_icono> banco_icono { get; set; }
    
        public virtual int ComprobarMantenimiento(Nullable<int> idPedido, ObjectParameter result)
        {
            var idPedidoParameter = idPedido.HasValue ?
                new ObjectParameter("idPedido", idPedido) :
                new ObjectParameter("idPedido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ComprobarMantenimiento", idPedidoParameter, result);
        }
    }
}
