//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class normas
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public string nombre_norma { get; set; }
        public string edicion_norma { get; set; }
        public int descargas { get; set; }
        public string enlace { get; set; }
    }
}
