//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class noticias
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string texto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> organizacion { get; set; }
        public Nullable<System.DateTime> fechaexp { get; set; }
        public Nullable<int> validada { get; set; }
        public string cabecera { get; set; }
    }
}
