//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class partes
    {
        public int id { get; set; }
        public string idcomunicacion { get; set; }
        public int idcentral { get; set; }
        public string empresa { get; set; }
        public string instalacion { get; set; }
        public string trabajo { get; set; }
        public string detalle { get; set; }
        public string accionescorrectoras { get; set; }
        public string accionesprevistas { get; set; }
        public string cumplimentadopor { get; set; }
        public Nullable<System.DateTime> cumplimentadofecha { get; set; }
        public string entregadopor { get; set; }
        public Nullable<System.DateTime> entregadofecha { get; set; }
        public string recibidounidadorg { get; set; }
        public Nullable<System.DateTime> recibidofecha { get; set; }
        public string resueltopor { get; set; }
        public Nullable<System.DateTime> resueltofecha { get; set; }
        public string observaciones { get; set; }
        public int idconsecutivo { get; set; }
        public string desest { get; set; }
        public Nullable<System.DateTime> desestfecha { get; set; }
        public string asunto { get; set; }
    }
}
