//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfil
    {
        public int id { get; set; }
        public string perfil1 { get; set; }
        public Nullable<int> permiso_general { get; set; }
        public Nullable<int> permiso_procesos { get; set; }
        public Nullable<int> permiso_objetivos { get; set; }
        public Nullable<int> permiso_formacion { get; set; }
        public Nullable<int> permiso_comunicacion { get; set; }
        public Nullable<int> permiso_accionesmejora { get; set; }
        public Nullable<int> permiso_auditorias { get; set; }
        public Nullable<int> permiso_emergencias { get; set; }
        public Nullable<int> permiso_reqlegales { get; set; }
        public Nullable<int> permiso_satisfaccion { get; set; }
        public Nullable<int> permiso_aspectos { get; set; }
        public Nullable<int> permiso_riesgos { get; set; }
        public Nullable<int> permiso_actas { get; set; }
        public Nullable<int> permiso_informes { get; set; }
        public Nullable<int> permiso_gestordoc { get; set; }
        public Nullable<int> permiso_gestortareas { get; set; }
        public Nullable<int> permiso_revisionenergetica { get; set; }
        public Nullable<int> permiso_datosindicadores { get; set; }
    }
}
