//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personas
    {
        public int Id { get; set; }
        public string Nº_Empleado { get; set; }
        public string Perfil_de_riesgo { get; set; }
        public string Actividad_Funcional { get; set; }
        public string DNI { get; set; }
        public string Nombre { get; set; }
        public string Empresa { get; set; }
        public string Centro_de_trabajo { get; set; }
        public string Actividad { get; set; }
        public string Unidad_Organizativa { get; set; }
        public string Jefe_Directo { get; set; }
        public string Posicion { get; set; }
        public string Ocupacion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public bool Activo { get; set; }
    }
}
