//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class procesos
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string tipo { get; set; }
        public string nivel { get; set; }
        public Nullable<int> padre { get; set; }
        public int organizacion { get; set; }
        public string cod_proceso { get; set; }
        public string diagrama { get; set; }
        public string objetivos { get; set; }
        public string alcance { get; set; }
        public string definiciones { get; set; }
        public string inicio { get; set; }
        public string final { get; set; }
        public string puntosrel { get; set; }
        public string resproc { get; set; }
        public string edicion { get; set; }
        public string fedicion { get; set; }
        public string frevision { get; set; }
        public string aprobado { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<int> tecnologia { get; set; }
    }
}
