//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class riesgos_medidas
    {
        public int id { get; set; }
        public Nullable<int> codigo { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_tecnologia { get; set; }
        public Nullable<int> id_riesgo { get; set; }
        public string imagen { get; set; }
        public Nullable<int> id_apartado { get; set; }
        public Nullable<int> id_centro { get; set; }
        public Nullable<int> imagen_grande { get; set; }
    }
}
