//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_Riesgo
    {
        public int Id { get; set; }
        public string CodigoRiesgo { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> idCadenaValor { get; set; }
        public Nullable<int> idMacroproceso { get; set; }
        public Nullable<int> idProceso { get; set; }
        public string categoria { get; set; }
        public string tipologia { get; set; }
        public string RI_ProbabilidadOcurrencia { get; set; }
        public string RI_ImpactoObjetivos { get; set; }
        public string RI_ImpactoEconomico { get; set; }
        public string RI_ImpactoProcesosNegocio { get; set; }
        public string RI_ImpactoReputacional { get; set; }
        public string RI_ImpactoCumplimiento { get; set; }
        public string RI_ImpactoGeneral { get; set; }
        public string RI_RelevanciaRiesgo { get; set; }
        public string RI_ValorRelevanciaRiesgo { get; set; }
        public string RI_GestionRiesgo { get; set; }
        public Nullable<bool> LimitOOE { get; set; }
        public Nullable<bool> LimitOO { get; set; }
        public Nullable<bool> LimitE { get; set; }
        public Nullable<bool> SinLimit { get; set; }
        public Nullable<bool> SinEfectos { get; set; }
        public Nullable<bool> EfectD { get; set; }
        public Nullable<bool> EfectDI { get; set; }
        public string ValoracionOportunidad { get; set; }
        public string GestionOportunidad { get; set; }
        public string DescripcionControl { get; set; }
        public string PropietarioControl { get; set; }
        public string RR_ProbabilidadOcurrencia { get; set; }
        public string RR_ImpactoObjetivos { get; set; }
        public string RR_ImpactoEconomico { get; set; }
        public string RR_ImpactoProcesosNegocio { get; set; }
        public string RR_ImpactoReputacional { get; set; }
        public string RR_ImpactoCumplimiento { get; set; }
        public string RR_ImpactoGeneral { get; set; }
        public string RR_RelevanciaRiesgo { get; set; }
        public string RR_ValorRelevanciaRiesgo { get; set; }
        public Nullable<int> idCentral { get; set; }
        public Nullable<int> idconsecutivo { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<int> vigente { get; set; }
    }
}
