//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_ListarCentrosAsignados
    {
        public int id { get; set; }
        public string siglas { get; set; }
        public string nombre { get; set; }
        public string tipo { get; set; }
        public string nombre_comunidad { get; set; }
        public int id_comunidad_autonoma { get; set; }
        public string nombre_provincia { get; set; }
        public int id_provincia { get; set; }
        public string permiso { get; set; }
        public int idusuario { get; set; }
    }
}
