//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_RequisitosLegales
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public Nullable<int> anio { get; set; }
        public string denominacion { get; set; }
        public string informeevaluacion { get; set; }
        public Nullable<System.DateTime> fecharegistro { get; set; }
        public Nullable<int> numrequisitos { get; set; }
        public Nullable<int> cumple { get; set; }
        public Nullable<int> tramite { get; set; }
        public Nullable<int> nocumple { get; set; }
        public Nullable<int> observacion { get; set; }
        public Nullable<int> noprocede { get; set; }
        public Nullable<int> noverificado { get; set; }
        public int idconsecutivo { get; set; }
        public Nullable<int> ambito { get; set; }
        public string nombre_ambito { get; set; }
        public int idcentral { get; set; }
    }
}
