//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_AspectoTipo
    {
        public int id { get; set; }
        public int Grupo { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Unidad { get; set; }
        public string NombreCompleto { get; set; }
    }
}
