//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_ListarEventosCalidad
    {
        public int id { get; set; }
        public string asunto { get; set; }
        public string compania { get; set; }
        public string pais { get; set; }
        public int idcentral { get; set; }
        public string unidad { get; set; }
        public Nullable<System.DateTime> fechacomienzo { get; set; }
        public Nullable<System.DateTime> fechafin { get; set; }
        public string evento { get; set; }
        public string codevento { get; set; }
        public string descripcion { get; set; }
        public string impacto { get; set; }
        public string cargo { get; set; }
        public string persona { get; set; }
    }
}
