//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_ListadoIndicadores
    {
        public int IdImputacion { get; set; }
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string MetodoMedicion { get; set; }
        public string nombreProceso { get; set; }
        public string Unidad { get; set; }
        public string nombretecnologia { get; set; }
        public string Descripcion { get; set; }
        public string Periodicidad { get; set; }
        public string Operacion { get; set; }
        public Nullable<int> anio { get; set; }
        public Nullable<decimal> ValorReferencia1 { get; set; }
        public Nullable<decimal> ValorReferencia2 { get; set; }
        public Nullable<decimal> ValorReferencia3 { get; set; }
        public Nullable<decimal> ValorReferencia4 { get; set; }
        public Nullable<decimal> ValorReferencia5 { get; set; }
        public Nullable<decimal> ValorReferencia6 { get; set; }
        public Nullable<decimal> ValorReferencia7 { get; set; }
        public Nullable<decimal> ValorReferencia8 { get; set; }
        public Nullable<decimal> ValorReferencia9 { get; set; }
        public Nullable<decimal> ValorReferencia10 { get; set; }
        public Nullable<decimal> ValorReferencia11 { get; set; }
        public Nullable<decimal> ValorReferencia12 { get; set; }
        public Nullable<decimal> Valoracion1 { get; set; }
        public Nullable<decimal> Valoracion2 { get; set; }
        public Nullable<decimal> Valoracion3 { get; set; }
        public Nullable<decimal> Valoracion4 { get; set; }
        public Nullable<decimal> Valoracion5 { get; set; }
        public Nullable<decimal> Valoracion6 { get; set; }
        public Nullable<decimal> Valoracion7 { get; set; }
        public Nullable<decimal> Valoracion8 { get; set; }
        public Nullable<decimal> Valoracion9 { get; set; }
        public Nullable<decimal> Valoracion10 { get; set; }
        public Nullable<decimal> Valoracion11 { get; set; }
        public Nullable<decimal> Valoracion12 { get; set; }
        public Nullable<decimal> ValorCalculado1 { get; set; }
        public Nullable<decimal> ValorCalculado2 { get; set; }
        public Nullable<decimal> ValorCalculado3 { get; set; }
        public Nullable<decimal> ValorCalculado4 { get; set; }
        public Nullable<decimal> ValorCalculado5 { get; set; }
        public Nullable<decimal> ValorCalculado6 { get; set; }
        public Nullable<decimal> ValorCalculado7 { get; set; }
        public Nullable<decimal> ValorCalculado8 { get; set; }
        public Nullable<decimal> ValorCalculado9 { get; set; }
        public Nullable<decimal> ValorCalculado10 { get; set; }
        public Nullable<decimal> ValorCalculado11 { get; set; }
        public Nullable<decimal> ValorCalculado12 { get; set; }
        public int idcentral { get; set; }
    }
}
