//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_ListarUsuarios
    {
        public int idUsuario { get; set; }
        public string login { get; set; }
        public Nullable<int> perfil { get; set; }
        public string perfilusuario { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string baja { get; set; }
        public string nombre { get; set; }
    }
}
