//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_Riesgos
    {
        public int Id { get; set; }
        public string CodigoRiesgo { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string Descripcion { get; set; }
        public string RI_ImpactoGeneral { get; set; }
        public string RI_RelevanciaRiesgo { get; set; }
        public string RR_ImpactoGeneral { get; set; }
        public string RR_RelevanciaRiesgo { get; set; }
        public Nullable<int> idCentral { get; set; }
        public string GestionOportunidad { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<int> vigente { get; set; }
    }
}
