//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_ParametrosInd
    {
        public int id { get; set; }
        public string proceso { get; set; }
        public string indicador { get; set; }
        public string periodicidad { get; set; }
        public string unidad { get; set; }
    }
}
