//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_Comunicaciones
    {
        public int id { get; set; }
        public string idcomunicacion { get; set; }
        public string tipo { get; set; }
        public string Clasificacion { get; set; }
        public string denominacion { get; set; }
        public Nullable<System.DateTime> fechainicio { get; set; }
        public string canal { get; set; }
        public string eficacia { get; set; }
        public Nullable<System.DateTime> fechafin { get; set; }
        public int idcentral { get; set; }
        public int stakeholder { get; set; }
        public int idcanal { get; set; }
        public string asunto { get; set; }
        public string remitente { get; set; }
    }
}
