//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_Eventos_Seguridad
    {
        public int id { get; set; }
        public string tipo { get; set; }
        public string severidad { get; set; }
        public string personalafectado { get; set; }
        public string organizacion { get; set; }
        public string pais { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public string unidadnegocio { get; set; }
        public string compania { get; set; }
        public string ie_region { get; set; }
        public string ie_localizacion { get; set; }
        public string ie_descripcion { get; set; }
        public string pa_nombre { get; set; }
        public string pa_apellido { get; set; }
        public string genero { get; set; }
        public int pa_edad { get; set; }
        public string pa_puesto { get; set; }
        public string pa_nacionalidad { get; set; }
        public string id_informemedico { get; set; }
        public string id_diasconv_primerpron { get; set; }
        public string te_tipo { get; set; }
        public string te_subtipo { get; set; }
        public int te_categorizacion { get; set; }
        public string te_causa { get; set; }
        public string te_accionesinm { get; set; }
        public string ic_nombreempresa { get; set; }
        public string ic_actividad { get; set; }
        public string ic_personaref { get; set; }
        public string ic_telefono { get; set; }
        public string ic_email { get; set; }
        public string ia_horario { get; set; }
        public string ia_desde { get; set; }
        public string ia_hacia { get; set; }
        public string ia_lugar { get; set; }
        public string ia_medio { get; set; }
        public string ia_propiedadmediotransporte { get; set; }
        public string ia_causa { get; set; }
        public int idcentral { get; set; }
    }
}
