//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_UltimasMediciones
    {
        public int Id { get; set; }
        public Nullable<decimal> ultimovalorCalc { get; set; }
        public Nullable<decimal> ultimovalorRef { get; set; }
        public Nullable<int> anio { get; set; }
        public int IdIndicador { get; set; }
        public int idcentral { get; set; }
        public Nullable<int> tendencia { get; set; }
    }
}
