//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_AspectosValoracion
    {
        public int id { get; set; }
        public string grupo { get; set; }
        public string Nombre { get; set; }
        public string Unidad { get; set; }
        public Nullable<decimal> anio1 { get; set; }
        public Nullable<decimal> anio2 { get; set; }
        public Nullable<decimal> anio3 { get; set; }
        public Nullable<decimal> anio4 { get; set; }
        public Nullable<decimal> anio5 { get; set; }
        public Nullable<decimal> anio6 { get; set; }
        public Nullable<int> idCentral { get; set; }
        public Nullable<int> significancia1 { get; set; }
        public Nullable<int> significancia2 { get; set; }
        public Nullable<int> significancia3 { get; set; }
        public Nullable<int> significancia4 { get; set; }
        public Nullable<int> significancia5 { get; set; }
        public Nullable<int> significancia6 { get; set; }
        public string Codigo { get; set; }
        public string descripcion { get; set; }
        public string categoria { get; set; }
        public Nullable<int> foco { get; set; }
        public string Expr1 { get; set; }
        public string nombrefoco { get; set; }
        public Nullable<int> queja { get; set; }
        public string quejaobs { get; set; }
        public string Impacto { get; set; }
        public Nullable<decimal> resmagnitud { get; set; }
        public Nullable<decimal> resnaturaleza { get; set; }
        public Nullable<decimal> resorigen { get; set; }
    }
}
