//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_ListarSatisfaccion
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public string denominacion { get; set; }
        public Nullable<System.DateTime> fecharealizacion { get; set; }
        public string nombre { get; set; }
        public string informe { get; set; }
        public string conclusiones { get; set; }
        public int idcentral { get; set; }
        public string personasinv { get; set; }
    }
}
