//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_ListarLogEvaluacionesFoco
    {
        public int id { get; set; }
        public Nullable<int> anio { get; set; }
        public string grupo { get; set; }
        public string Nombre { get; set; }
        public string Unidad { get; set; }
        public string descripcion { get; set; }
        public string Impacto { get; set; }
        public Nullable<decimal> resmagnitud { get; set; }
        public Nullable<decimal> resnaturaleza { get; set; }
        public Nullable<decimal> resorigen { get; set; }
        public Nullable<int> queja { get; set; }
        public Nullable<int> significancia { get; set; }
        public Nullable<int> idCentral { get; set; }
        public string Codigo { get; set; }
        public string Expr1 { get; set; }
        public string identificacion { get; set; }
        public Nullable<decimal> valoranio { get; set; }
        public Nullable<decimal> variacion { get; set; }
        public Nullable<decimal> acercamiento { get; set; }
        public Nullable<decimal> referencia { get; set; }
        public Nullable<decimal> datoabsoluto { get; set; }
        public string quejaobs { get; set; }
        public Nullable<int> id_registro { get; set; }
        public string codaspcentral { get; set; }
    }
}
