//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_ListarComunidadesEdicion
    {
        public int id_comunidad_autonoma { get; set; }
        public int id_pais { get; set; }
        public string nombre_comunidad { get; set; }
        public string nombre_pais { get; set; }
    }
}
