//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_ListarEventosAmbientales
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fechaevento { get; set; }
        public string tipo { get; set; }
        public string matrizprincipal { get; set; }
        public string matrizsecundaria { get; set; }
        public string organizacion { get; set; }
        public string pais { get; set; }
        public string unidadnegocio { get; set; }
        public int idcentral { get; set; }
        public string companiainvolucrada { get; set; }
        public string companiaenel { get; set; }
        public string clase_evento { get; set; }
    }
}
