//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_ObtenerUsuario
    {
        public int idUsuario { get; set; }
        public string nombre { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<bool> baja { get; set; }
        public string nombreap { get; set; }
        public string mail { get; set; }
        public string telefono { get; set; }
        public string puesto { get; set; }
        public Nullable<int> perfil { get; set; }
        public Nullable<int> idUnidad { get; set; }
    }
}
